---
title: "Dynamic report"
output: html_document
params:
  c: NA
  s: NA
  t: NA
  q: NA
  v: NA
  f: NA
  p: NA
  data1: NA
  data2: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, comment = NA, error = F,warning = F, message = F)
```

**Data exploratory**

+ User selection from CA table

```{r, include=F}
Country<-params$c
Species<-params$s
Sampling.type<-params$t
Quarter<-params$q
Variable.selected<-params$v
```

```{r}
Country
Species
Sampling.type
Quarter
Variable.selected

```

**Map**

```{r, echo=F}
leaflet(params$data2, height=800, width=900) %>% 
  addProviderTiles(providers$CartoDB.Positron)%>% 
  setView(lng = -5,lat =  50, zoom = 5)%>%
  addCircleMarkers(color=~params$p(aux),
                     stroke=F,
                     radius=~ (sqrt(sqrt(aux))+0.6),
                     fillOpacity=0.8)%>%
  addLegend( "bottomleft", pal=params$p, values=~aux, title = params$v,opacity = 0.8)
  
```

**Barplot**

```{r, echo=F}
      ggplot(params$data1, aes(x=FlagCountry, y=aux, fill=FlagCountry)) +
         geom_bar(stat="identity")+
         params$f +
         theme_bw()+
         theme(axis.text.x = element_text(angle = 90, hjust = 1))+
         labs(y = params$v)
```
